/*  DriftingDroids - yet another Ricochet Robots solver program.
    Copyright (C) 2011-2025 Michael Henke

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package driftingdroids.model

import kotlin.concurrent.Volatile
import kotlin.math.max

/**
 * This class is a minimal `Map&ltK,V&gt` implementation for primitive
 * `int` or `long` keys K and <tt>byte</tt> values V,
 * based on a trie (prefix tree) data structure.
 * 
 * 
 * The aim is to balance a fast recognition of duplicate keys
 * and a compact storage of data.
 * 
 * 
 * This class is called "special" because it's specialized to work with keys
 * that are generated by the `KeyMakerInt` or `KeyMakerLong`
 * classes, only. That means that it relies on the specific properties of these keys,
 * which are:<br></br>
 * * keys consist of N elements: the positions of the N robots on the board<br></br>
 * * all elements 1...N of a key are unique: no two robots are on the same position<br></br>
 * * elements 1...N-1 of a key are sorted: non-goal robots can be substituted for each other<br></br>
 * 
 */
open class KeyDepthMapTrieSpecial private constructor(board: Board) : KeyDepthMap {
    protected val rootNode: IntArray
    protected var nodeArrays: Array<IntArray>
    protected var numNodeArrays: Int
    protected var nextNode: Int
    protected var nextNodeArray: Int

    protected var leafArrays: Array<ByteArray>
    protected var numLeafArrays: Int
    protected var nextLeaf: Int
    protected var nextLeafArray: Int

    protected val nodeNumber: Int
    protected val nodeNumberUnCompr: Int
    protected val nodeShift: Int
    protected val nodeMask: Int
    protected val leafNodeShift: Int
    protected val leafNodeMask: Int
    protected val leafNodeSize: Int
    protected val leafSize: Int
    protected val leafMask: Int

    protected val nodeSizeLookup: IntArray
    protected val elementLookup: IntArray

    protected var size: Int = 0

    // Hard limit on total arrays to prevent OOM (calculated from heap size)
    protected val maxNodeArrays: Int
    protected val maxLeafArrays: Int

    @Volatile
    protected var allocationLimitReached: Boolean = false

    init {
        this.nodeSizeLookup = IntArray(board.size)
        for (i in this.nodeSizeLookup.indices) {
            this.nodeSizeLookup[i] = board.size - 1 - i
        }
        this.elementLookup = IntArray(board.size)
        for (i in this.elementLookup.indices) {
            this.elementLookup[i] = i
        }
        for (i in 0..<board.size) {
            if (true == board.isObstacle(i)) {
                for (j in 0..<i) {
                    this.nodeSizeLookup[j] -= 1
                }
                for (j in i..<this.elementLookup.size) {
                    this.elementLookup[j] -= 1
                }
            }
        }
        for (i in 0..<board.size) {
            if (true == board.isObstacle(i)) {
                this.nodeSizeLookup[i] = Int.MIN_VALUE
                this.elementLookup[i] = Int.MIN_VALUE
            }
        }
        val numRobots = board.numRobots - (if (board.isSolution01) 1 else 0)
        this.nodeNumber = numRobots - 1
        this.nodeNumberUnCompr =
            (numRobots * board.sizeNumBits + 8 - 31 + (board.sizeNumBits - 1)) / board.sizeNumBits
        this.nodeShift = board.sizeNumBits
        this.nodeMask = (1 shl board.sizeNumBits) - 1

        // Calculate hard allocation limits from heap size (25% for nodes, 10% for leaves)
        val maxHeap = Runtime.getRuntime().maxMemory()
        this.maxNodeArrays = max(16, ((maxHeap / 4) / (NODE_ARRAY_SIZE * 4L)).toInt())
        this.maxLeafArrays = max(16, ((maxHeap / 10) / LEAF_ARRAY_SIZE).toInt())

        this.nodeArrays = Array(64) { IntArray(NODE_ARRAY_SIZE) }
        this.rootNode = this.nodeArrays[0]!!
        this.numNodeArrays = 1
        this.nextNode = board.size //root node already exists
        this.nextNodeArray = NODE_ARRAY_SIZE //first array already exists

        this.leafNodeShift = board.sizeNumBits / 2
        this.leafNodeMask = (1 shl this.leafNodeShift) - 1
        this.leafNodeSize = this.leafNodeMask + 1
        this.leafSize = 1 shl (board.sizeNumBits - this.leafNodeShift)
        this.leafMask = this.leafSize - 1
        this.leafArrays = Array(64) { ByteArray(LEAF_ARRAY_SIZE) }
        this.numLeafArrays = 0
        this.nextLeaf =
            this.leafSize //no leaves yet, but skip leaf "0" because this is the special value
        this.nextLeafArray = 0 //no leaf arrays yet
    }


    // Central allocation methods with hard limits to prevent OOM
    protected fun tryAllocateNodeArray(): IntArray? {
        if (this.numNodeArrays >= this.maxNodeArrays) {
            this.allocationLimitReached = true
            return null
        }
        try {
            return IntArray(NODE_ARRAY_SIZE)
        } catch (oom: OutOfMemoryError) {
            this.allocationLimitReached = true
            return null
        }
    }

    protected fun tryAllocateLeafArray(): ByteArray? {
        if (this.numLeafArrays >= this.maxLeafArrays) {
            this.allocationLimitReached = true
            return null
        }
        try {
            return ByteArray(LEAF_ARRAY_SIZE)
        } catch (oom: OutOfMemoryError) {
            this.allocationLimitReached = true
            return null
        }
    }

    /* (non-Javadoc)
     * @see driftingdroids.model.KeyDepthMap#putIfGreater(int, int)
     */
    override fun putIfGreater(key: Int, byteValue: Int): Boolean {
        var key = key
        if (this.allocationLimitReached) return false
        //root node
        var nidx = key and this.nodeMask
        var nodeArray = this.rootNode
        var elementThis = nidx
        var elementThisLookup = this.elementLookup[nidx]
        //go through nodes (without compression because (key<<8)+value is greater than "int")
        var nodeIndex: Int
        var i: Int //used by both for() loops
        i = 1
        while (i < this.nodeNumberUnCompr) {
            nodeIndex = nodeArray[nidx]
            key = key ushr this.nodeShift
            if (0 == nodeIndex) {
                //create a new node
                val nodeSize = this.nodeSizeLookup[elementThis]
                if (this.nextNode + nodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += nodeSize
                nodeArray[nidx] = nodeIndex
            }
            elementThis = key and this.nodeMask
            nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
            elementThisLookup = this.elementLookup[elementThis]
            nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            nidx += elementThisLookup
            ++i
        }
        //go through nodes (with compression because (key<<8)+value is inside "int" range now)
        while (i < this.nodeNumber) {
            nodeIndex = nodeArray[nidx]
            key = key ushr this.nodeShift
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                nodeArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key) {
                    if (byteValue > prevVal) {  //putIfGreater
                        nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                val nodeSize = this.nodeSizeLookup[elementThis]
                if (this.nextNode + nodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += nodeSize
                nodeArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                elementThis = key and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray[nidx + this.elementLookup[prevKey and this.nodeMask]] =
                    ((prevKey ushr this.nodeShift).inv() shl 8) or prevVal
            } else {
                // -> node index is positive = go to next node
                elementThis = key and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx += elementThisLookup
            ++i
        }
        //go through leaf node (with compression)
        nodeIndex = nodeArray[nidx]
        key = key ushr this.nodeShift
        if (0 == nodeIndex) {
            // -> node index is null = unused
            //write current key+value as a "compressed branch" (negative node index)
            //exit immediately because no further nodes and no leaf need to be stored
            nodeArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
            return true
        } else if (0 > nodeIndex) {
            // -> node index is negative = used by a single "compressed branch"
            val prevKey = (nodeIndex.inv()) shr 8
            val prevVal = 0xff and nodeIndex
            //previous and current keys are equal (duplicate key)
            if (prevKey == key) {
                if (byteValue > prevVal) {  //putIfGreater
                    nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                    return true
                }
                return false
            }
            //previous and current keys are not equal
            //create a new node
            if (this.nextNode + this.leafNodeSize > this.nextNodeArray) {
                if (this.nodeArrays.size <= this.numNodeArrays) {
                    this.nodeArrays = this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                }
                val newNodeArray = tryAllocateNodeArray()
                if (newNodeArray == null) return false
                this.nodeArrays[this.numNodeArrays++] = newNodeArray
                this.nextNode = this.nextNodeArray
                this.nextNodeArray += NODE_ARRAY_SIZE
            }
            nodeIndex = this.nextNode
            this.nextNode += this.leafNodeSize
            nodeArray[nidx] = nodeIndex
            //push previous "compressed branch" one node further
            nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            nidx = (nodeIndex and NODE_ARRAY_MASK) + (prevKey and this.leafNodeMask)
            nodeArray[nidx] = ((prevKey ushr this.leafNodeShift).inv() shl 8) or prevVal //negative
        } else {
            // -> node index is positive = go to next node
            nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
        }
        nidx = (nodeIndex and NODE_ARRAY_MASK) + (key and this.leafNodeMask)
        //get leaf (with compression)
        var leafIndex = nodeArray[nidx]
        key = key ushr this.leafNodeShift
        if (0 == leafIndex) {
            // -> leaf index is null = unused
            //write current value as a "compressed branch" (negative leaf index)
            //exit immediately because no leaf needs to be stored
            nodeArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
            return true
        } else if (0 > leafIndex) {
            // -> leaf index is negative = used by a single "compressed branch"
            val prevKey = (leafIndex.inv()) shr 8
            val prevVal = 0xff and leafIndex
            //previous and current keys are equal (duplicate key)
            if (prevKey == key) {
                if (byteValue > prevVal) {  //putIfGreater
                    nodeArray[nidx] = (leafIndex xor prevVal) or byteValue //negative
                    return true
                }
                return false
            }
            //previous and current keys are not equal
            //create a new leaf
            if (this.nextLeaf >= this.nextLeafArray) {
                if (this.leafArrays.size <= this.numLeafArrays) {
                    this.leafArrays = this.leafArrays.copyOf<ByteArray>(this.leafArrays.size shl 1) as Array<ByteArray>
                }
                val newLeafArray = tryAllocateLeafArray()
                if (newLeafArray == null) return false
                this.leafArrays[this.numLeafArrays++] = newLeafArray
                this.nextLeafArray += LEAF_ARRAY_SIZE
            }
            leafIndex = this.nextLeaf
            this.nextLeaf += this.leafSize
            nodeArray[nidx] = leafIndex
            //push the previous "compressed branch" further to the leaf
            val lidx = (leafIndex and LEAF_ARRAY_MASK) + (prevKey and this.leafMask)
            this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT][lidx] = prevVal.toByte()
        }
        val leafArray = this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT]
        val lidx = (leafIndex and LEAF_ARRAY_MASK) + (key and this.leafMask)
        val prevVal = leafArray[lidx]
        if (byteValue > (0xff and prevVal.toInt())) {  //putIfGreater
            leafArray[lidx] = byteValue.toByte()
            return true
        }
        return false
    }


    /* (non-Javadoc)
     * @see driftingdroids.model.KeyDepthMap#putIfGreater(long, int)
     */
    override fun putIfGreater(key: Long, byteValue: Int): Boolean {
        //this method is copy&paste from putIfGreater(int,int) with only a few (int) casts added where required.
        //root node
        var key = key
        var nidx = key.toInt() and this.nodeMask
        var nodeArray = this.rootNode
        var elementThis = nidx
        var elementThisLookup = this.elementLookup[nidx]
        //go through nodes (without compression because (key<<8)+value is greater than "int")
        var nodeIndex: Int
        var i: Int //used by both for() loops
        i = 1
        while (i < this.nodeNumberUnCompr) {
            nodeIndex = nodeArray[nidx]
            key = key ushr this.nodeShift
            if (0 == nodeIndex) {
                //create a new node
                val nodeSize = this.nodeSizeLookup[elementThis]
                if (this.nextNode + nodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += nodeSize
                nodeArray[nidx] = nodeIndex
            }
            elementThis = key.toInt() and this.nodeMask
            nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
            elementThisLookup = this.elementLookup[elementThis]
            nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            nidx += elementThisLookup
            ++i
        }
        //go through nodes (with compression because (key<<8)+value is inside "int" range now)
        while (i < this.nodeNumber) {
            nodeIndex = nodeArray[nidx]
            key = key ushr this.nodeShift
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key.toInt()) {
                    if (byteValue > prevVal) {  //putIfGreater
                        nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                val nodeSize = this.nodeSizeLookup[elementThis]
                if (this.nextNode + nodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += nodeSize
                nodeArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                elementThis = key.toInt() and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray[nidx + this.elementLookup[prevKey and this.nodeMask]] =
                    ((prevKey ushr this.nodeShift).inv() shl 8) or prevVal
            } else {
                // -> node index is positive = go to next node
                elementThis = key.toInt() and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx += elementThisLookup
            ++i
        }
        //go through leaf node (with compression)
        nodeIndex = nodeArray[nidx]
        key = key ushr this.nodeShift
        if (0 == nodeIndex) {
            // -> node index is null = unused
            //write current key+value as a "compressed branch" (negative node index)
            //exit immediately because no further nodes and no leaf need to be stored
            nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
            return true
        } else if (0 > nodeIndex) {
            // -> node index is negative = used by a single "compressed branch"
            val prevKey = (nodeIndex.inv()) shr 8
            val prevVal = 0xff and nodeIndex
            //previous and current keys are equal (duplicate key)
            if (prevKey == key.toInt()) {
                if (byteValue > prevVal) {  //putIfGreater
                    nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                    return true
                }
                return false
            }
            //previous and current keys are not equal
            //create a new node
            if (this.nextNode + this.leafNodeSize > this.nextNodeArray) {
                if (this.nodeArrays.size <= this.numNodeArrays) {
                    this.nodeArrays = this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                }
                val newNodeArray = tryAllocateNodeArray()
                if (newNodeArray == null) return false
                this.nodeArrays[this.numNodeArrays++] = newNodeArray
                this.nextNode = this.nextNodeArray
                this.nextNodeArray += NODE_ARRAY_SIZE
            }
            nodeIndex = this.nextNode
            this.nextNode += this.leafNodeSize
            nodeArray[nidx] = nodeIndex
            //push previous "compressed branch" one node further
            nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            nidx = (nodeIndex and NODE_ARRAY_MASK) + (prevKey and this.leafNodeMask)
            nodeArray[nidx] = ((prevKey ushr this.leafNodeShift).inv() shl 8) or prevVal //negative
        } else {
            // -> node index is positive = go to next node
            nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
        }
        nidx = (nodeIndex and NODE_ARRAY_MASK) + (key.toInt() and this.leafNodeMask)
        //get leaf (with compression)
        var leafIndex = nodeArray[nidx]
        key = key ushr this.leafNodeShift
        if (0 == leafIndex) {
            // -> leaf index is null = unused
            //write current value as a "compressed branch" (negative leaf index)
            //exit immediately because no leaf needs to be stored
            nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
            return true
        } else if (0 > leafIndex) {
            // -> leaf index is negative = used by a single "compressed branch"
            val prevKey = (leafIndex.inv()) shr 8
            val prevVal = 0xff and leafIndex
            //previous and current keys are equal (duplicate key)
            if (prevKey == key.toInt()) {
                if (byteValue > prevVal) {  //putIfGreater
                    nodeArray[nidx] = (leafIndex xor prevVal) or byteValue //negative
                    return true
                }
                return false
            }
            //previous and current keys are not equal
            //create a new leaf
            if (this.nextLeaf >= this.nextLeafArray) {
                if (this.leafArrays.size <= this.numLeafArrays) {
                    this.leafArrays = this.leafArrays.copyOf<ByteArray>(this.leafArrays.size shl 1) as Array<ByteArray>
                }
                val newLeafArray = tryAllocateLeafArray()
                if (newLeafArray == null) return false
                this.leafArrays[this.numLeafArrays++] = newLeafArray
                this.nextLeafArray += LEAF_ARRAY_SIZE
            }
            leafIndex = this.nextLeaf
            this.nextLeaf += this.leafSize
            nodeArray[nidx] = leafIndex
            //push the previous "compressed branch" further to the leaf
            val lidx = (leafIndex and LEAF_ARRAY_MASK) + (prevKey and this.leafMask)
            this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT][lidx] = prevVal.toByte()
        }
        val leafArray = this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT]
        val lidx = (leafIndex and LEAF_ARRAY_MASK) + (key.toInt() and this.leafMask)
        val prevVal = leafArray[lidx]
        if (byteValue > (0xff and prevVal.toInt())) {  //putIfGreater
            leafArray[lidx] = byteValue.toByte()
            return true
        }
        return false
    }


    /* (non-Javadoc)
     * @see driftingdroids.model.KeyDepthMap#allocatedBytes()
     */
    override fun allocatedBytes(): Long {
        var result = (this.nodeArrays.size + this.leafArrays.size) * 8L
        for (i in 0..<this.numNodeArrays) {
            result += this.nodeArrays[i].size * 4L
        }
        for (i in 0..<this.numLeafArrays) {
            result += this.leafArrays[i].size.toLong()
        }
        return result
    }


    /* (non-Javadoc)
     * @see driftingdroids.model.KeyDepthMap#size()
     */
    override fun size(): Int {
        return this.size
    }


    /**
     * this class is used to find a larger number of distinct, equally good solutions,
     * especially those that share some robot positions and would normally be excluded
     * by the aggressive search tree pruning.
     * the methods "putIfGreater" are modified to behave like "putIfGreaterOrEqual".
     * (the code is copied from the super class, changed lines are marked with //putIfGreaterOrEqual)
     */
    private class KeyDepthMapTrieSpecialEqual(board: Board) : KeyDepthMapTrieSpecial(board) {
        override fun putIfGreater(key: Int, byteValue: Int): Boolean {
            //root node
            var key = key
            var nidx = key and this.nodeMask
            var nodeArray = this.rootNode
            var elementThis = nidx
            var elementThisLookup = this.elementLookup[nidx]
            //go through nodes (without compression because (key<<8)+value is greater than "int")
            var nodeIndex: Int
            var i: Int //used by both for() loops
            i = 1
            while (i < this.nodeNumberUnCompr) {
                nodeIndex = nodeArray[nidx]
                key = key ushr this.nodeShift
                if (0 == nodeIndex) {
                    //create a new node
                    val nodeSize = this.nodeSizeLookup[elementThis]
                    if (this.nextNode + nodeSize > this.nextNodeArray) {
                        if (this.nodeArrays.size <= this.numNodeArrays) {
                            this.nodeArrays =
                                this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                        }
                        val newNodeArray = tryAllocateNodeArray()
                        if (newNodeArray == null) return false
                        this.nodeArrays[this.numNodeArrays++] = newNodeArray
                        this.nextNode = this.nextNodeArray
                        this.nextNodeArray += NODE_ARRAY_SIZE
                    }
                    nodeIndex = this.nextNode
                    this.nextNode += nodeSize
                    nodeArray[nidx] = nodeIndex
                }
                elementThis = key and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                nidx += elementThisLookup
                ++i
            }
            //go through nodes (with compression because (key<<8)+value is inside "int" range now)
            while (i < this.nodeNumber) {
                nodeIndex = nodeArray[nidx]
                key = key ushr this.nodeShift
                if (0 == nodeIndex) {
                    // -> node index is null = unused
                    //write current key+value as a "compressed branch" (negative node index)
                    //exit immediately because no further nodes and no leaf need to be stored
                    nodeArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
                    return true
                } else if (0 > nodeIndex) {
                    // -> node index is negative = used by a single "compressed branch"
                    val prevKey = (nodeIndex.inv()) shr 8
                    val prevVal = 0xff and nodeIndex
                    //previous and current keys are equal (duplicate key)
                    if (prevKey == key) {
                        if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                            nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                            return true
                        }
                        return false
                    }
                    //previous and current keys are not equal
                    //create a new node
                    val nodeSize = this.nodeSizeLookup[elementThis]
                    if (this.nextNode + nodeSize > this.nextNodeArray) {
                        if (this.nodeArrays.size <= this.numNodeArrays) {
                            this.nodeArrays =
                                this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                        }
                        val newNodeArray = tryAllocateNodeArray()
                        if (newNodeArray == null) return false
                        this.nodeArrays[this.numNodeArrays++] = newNodeArray
                        this.nextNode = this.nextNodeArray
                        this.nextNodeArray += NODE_ARRAY_SIZE
                    }
                    nodeIndex = this.nextNode
                    this.nextNode += nodeSize
                    nodeArray[nidx] = nodeIndex
                    //push previous "compressed branch" one node further
                    nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                    elementThis = key and this.nodeMask
                    nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                    elementThisLookup = this.elementLookup[elementThis]
                    nodeArray[nidx + this.elementLookup[prevKey and this.nodeMask]] =
                        ((prevKey ushr this.nodeShift).inv() shl 8) or prevVal
                } else {
                    // -> node index is positive = go to next node
                    elementThis = key and this.nodeMask
                    nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                    elementThisLookup = this.elementLookup[elementThis]
                    nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                }
                nidx += elementThisLookup
                ++i
            }
            //go through leaf node (with compression)
            nodeIndex = nodeArray[nidx]
            key = key ushr this.nodeShift
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                nodeArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key) {
                    if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                        nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                if (this.nextNode + this.leafNodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += this.leafNodeSize
                nodeArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                nidx = (nodeIndex and NODE_ARRAY_MASK) + (prevKey and this.leafNodeMask)
                nodeArray[nidx] =
                    ((prevKey ushr this.leafNodeShift).inv() shl 8) or prevVal //negative
            } else {
                // -> node index is positive = go to next node
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx = (nodeIndex and NODE_ARRAY_MASK) + (key and this.leafNodeMask)
            //get leaf (with compression)
            var leafIndex = nodeArray[nidx]
            key = key ushr this.leafNodeShift
            if (0 == leafIndex) {
                // -> leaf index is null = unused
                //write current value as a "compressed branch" (negative leaf index)
                //exit immediately because no leaf needs to be stored
                nodeArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > leafIndex) {
                // -> leaf index is negative = used by a single "compressed branch"
                val prevKey = (leafIndex.inv()) shr 8
                val prevVal = 0xff and leafIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key) {
                    if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                        nodeArray[nidx] = (leafIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new leaf
                if (this.nextLeaf >= this.nextLeafArray) {
                    if (this.leafArrays.size <= this.numLeafArrays) {
                        this.leafArrays =
                            this.leafArrays.copyOf<ByteArray>(this.leafArrays.size shl 1) as Array<ByteArray>
                    }
                    val newLeafArray = tryAllocateLeafArray()
                    if (newLeafArray == null) return false
                    this.leafArrays[this.numLeafArrays++] = newLeafArray
                    this.nextLeafArray += LEAF_ARRAY_SIZE
                }
                leafIndex = this.nextLeaf
                this.nextLeaf += this.leafSize
                nodeArray[nidx] = leafIndex
                //push the previous "compressed branch" further to the leaf
                val lidx = (leafIndex and LEAF_ARRAY_MASK) + (prevKey and this.leafMask)
                this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT][lidx] = prevVal.toByte()
            }
            val leafArray = this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT]
            val lidx = (leafIndex and LEAF_ARRAY_MASK) + (key and this.leafMask)
            val prevVal = leafArray[lidx]
            if (byteValue >= (0xff and prevVal.toInt())) {  //putIfGreaterOrEqual
                leafArray[lidx] = byteValue.toByte()
                return true
            }
            return false
        }

        override fun putIfGreater(key: Long, byteValue: Int): Boolean {
            //this method is copy&paste from putIfGreater(int,int) with only a few (int) casts added where required.
            //root node
            var key = key
            var nidx = key.toInt() and this.nodeMask
            var nodeArray = this.rootNode
            var elementThis = nidx
            var elementThisLookup = this.elementLookup[nidx]
            //go through nodes (without compression because (key<<8)+value is greater than "int")
            var nodeIndex: Int
            var i: Int //used by both for() loops
            i = 1
            while (i < this.nodeNumberUnCompr) {
                nodeIndex = nodeArray[nidx]
                key = key ushr this.nodeShift
                if (0 == nodeIndex) {
                    //create a new node
                    val nodeSize = this.nodeSizeLookup[elementThis]
                    if (this.nextNode + nodeSize > this.nextNodeArray) {
                        if (this.nodeArrays.size <= this.numNodeArrays) {
                            this.nodeArrays =
                                this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                        }
                        val newNodeArray = tryAllocateNodeArray()
                        if (newNodeArray == null) return false
                        this.nodeArrays[this.numNodeArrays++] = newNodeArray
                        this.nextNode = this.nextNodeArray
                        this.nextNodeArray += NODE_ARRAY_SIZE
                    }
                    nodeIndex = this.nextNode
                    this.nextNode += nodeSize
                    nodeArray[nidx] = nodeIndex
                }
                elementThis = key.toInt() and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                nidx += elementThisLookup
                ++i
            }
            //go through nodes (with compression because (key<<8)+value is inside "int" range now)
            while (i < this.nodeNumber) {
                nodeIndex = nodeArray[nidx]
                key = key ushr this.nodeShift
                if (0 == nodeIndex) {
                    // -> node index is null = unused
                    //write current key+value as a "compressed branch" (negative node index)
                    //exit immediately because no further nodes and no leaf need to be stored
                    nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                    return true
                } else if (0 > nodeIndex) {
                    // -> node index is negative = used by a single "compressed branch"
                    val prevKey = (nodeIndex.inv()) shr 8
                    val prevVal = 0xff and nodeIndex
                    //previous and current keys are equal (duplicate key)
                    if (prevKey == key.toInt()) {
                        if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                            nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                            return true
                        }
                        return false
                    }
                    //previous and current keys are not equal
                    //create a new node
                    val nodeSize = this.nodeSizeLookup[elementThis]
                    if (this.nextNode + nodeSize > this.nextNodeArray) {
                        if (this.nodeArrays.size <= this.numNodeArrays) {
                            this.nodeArrays =
                                this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                        }
                        val newNodeArray = tryAllocateNodeArray()
                        if (newNodeArray == null) return false
                        this.nodeArrays[this.numNodeArrays++] = newNodeArray
                        this.nextNode = this.nextNodeArray
                        this.nextNodeArray += NODE_ARRAY_SIZE
                    }
                    nodeIndex = this.nextNode
                    this.nextNode += nodeSize
                    nodeArray[nidx] = nodeIndex
                    //push previous "compressed branch" one node further
                    nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                    elementThis = key.toInt() and this.nodeMask
                    nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                    elementThisLookup = this.elementLookup[elementThis]
                    nodeArray[nidx + this.elementLookup[prevKey and this.nodeMask]] =
                        ((prevKey ushr this.nodeShift).inv() shl 8) or prevVal
                } else {
                    // -> node index is positive = go to next node
                    elementThis = key.toInt() and this.nodeMask
                    nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                    elementThisLookup = this.elementLookup[elementThis]
                    nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                }
                nidx += elementThisLookup
                ++i
            }
            //go through leaf node (with compression)
            nodeIndex = nodeArray[nidx]
            key = key ushr this.nodeShift
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key.toInt()) {
                    if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                        nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                if (this.nextNode + this.leafNodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += this.leafNodeSize
                nodeArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                nidx = (nodeIndex and NODE_ARRAY_MASK) + (prevKey and this.leafNodeMask)
                nodeArray[nidx] =
                    ((prevKey ushr this.leafNodeShift).inv() shl 8) or prevVal //negative
            } else {
                // -> node index is positive = go to next node
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx = (nodeIndex and NODE_ARRAY_MASK) + (key.toInt() and this.leafNodeMask)
            //get leaf (with compression)
            var leafIndex = nodeArray[nidx]
            key = key ushr this.leafNodeShift
            if (0 == leafIndex) {
                // -> leaf index is null = unused
                //write current value as a "compressed branch" (negative leaf index)
                //exit immediately because no leaf needs to be stored
                nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > leafIndex) {
                // -> leaf index is negative = used by a single "compressed branch"
                val prevKey = (leafIndex.inv()) shr 8
                val prevVal = 0xff and leafIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key.toInt()) {
                    if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                        nodeArray[nidx] = (leafIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new leaf
                if (this.nextLeaf >= this.nextLeafArray) {
                    if (this.leafArrays.size <= this.numLeafArrays) {
                        this.leafArrays =
                            this.leafArrays.copyOf<ByteArray>(this.leafArrays.size shl 1) as Array<ByteArray>
                    }
                    val newLeafArray = tryAllocateLeafArray()
                    if (newLeafArray == null) return false
                    this.leafArrays[this.numLeafArrays++] = newLeafArray
                    this.nextLeafArray += LEAF_ARRAY_SIZE
                }
                leafIndex = this.nextLeaf
                this.nextLeaf += this.leafSize
                nodeArray[nidx] = leafIndex
                //push the previous "compressed branch" further to the leaf
                val lidx = (leafIndex and LEAF_ARRAY_MASK) + (prevKey and this.leafMask)
                this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT][lidx] = prevVal.toByte()
            }
            val leafArray = this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT]
            val lidx = (leafIndex and LEAF_ARRAY_MASK) + (key.toInt() and this.leafMask)
            val prevVal = leafArray[lidx]
            if (byteValue >= (0xff and prevVal.toInt())) {  //putIfGreaterOrEqual
                leafArray[lidx] = byteValue.toByte()
                return true
            }
            return false
        }
    }


    /**
     * this class is a further specialization which trades some more memory for a speedup.
     * it can only be used for board size of 8 bits (256 == 16x16) and with 4 or 5 robots.
     */
    private open class KeyDepthMapTrieSpecial8Bit(board: Board) : KeyDepthMapTrieSpecial(board) {
        protected val lookupArray: IntArray

        init {
            this.lookupArray = IntArray(LOOKUP_MASK + 1) // 64 MiB
        }

        override fun putIfGreater(key: Int, byteValue: Int): Boolean { // for 4 robots
            var key = key
            var nidx = key and LOOKUP_MASK
            var nodeIndex = this.lookupArray[nidx]
            val nodeArray: IntArray
            key = key ushr LOOKUP_SHIFT
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                this.lookupArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key) {
                    if (byteValue > prevVal) {  //putIfGreater
                        this.lookupArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                if (this.nextNode + this.leafNodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += this.leafNodeSize
                this.lookupArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                nidx = (nodeIndex and NODE_ARRAY_MASK) + (prevKey and this.leafNodeMask)
                nodeArray[nidx] =
                    ((prevKey ushr this.leafNodeShift).inv() shl 8) or prevVal //negative
            } else {
                // -> node index is positive = go to next node
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx = (nodeIndex and NODE_ARRAY_MASK) + (key and this.leafNodeMask)
            //get leaf (with compression)
            var leafIndex = nodeArray[nidx]
            key = key ushr this.leafNodeShift
            if (0 == leafIndex) {
                // -> leaf index is null = unused
                //write current value as a "compressed branch" (negative leaf index)
                //exit immediately because no leaf needs to be stored
                nodeArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > leafIndex) {
                // -> leaf index is negative = used by a single "compressed branch"
                val prevKey = (leafIndex.inv()) shr 8
                val prevVal = 0xff and leafIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key) {
                    if (byteValue > prevVal) {  //putIfGreater
                        nodeArray[nidx] = (leafIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new leaf
                if (this.nextLeaf >= this.nextLeafArray) {
                    if (this.leafArrays.size <= this.numLeafArrays) {
                        this.leafArrays =
                            this.leafArrays.copyOf<ByteArray>(this.leafArrays.size shl 1) as Array<ByteArray>
                    }
                    val newLeafArray = tryAllocateLeafArray()
                    if (newLeafArray == null) return false
                    this.leafArrays[this.numLeafArrays++] = newLeafArray
                    this.nextLeafArray += LEAF_ARRAY_SIZE
                }
                leafIndex = this.nextLeaf
                this.nextLeaf += this.leafSize
                nodeArray[nidx] = leafIndex
                //push the previous "compressed branch" further to the leaf
                val lidx = (leafIndex and LEAF_ARRAY_MASK) + (prevKey and this.leafMask)
                this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT][lidx] = prevVal.toByte()
            }
            val leafArray = this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT]
            val lidx = (leafIndex and LEAF_ARRAY_MASK) + (key and this.leafMask)
            val prevVal = leafArray[lidx]
            if (byteValue > (0xff and prevVal.toInt())) {  //putIfGreater
                leafArray[lidx] = byteValue.toByte()
                return true
            }
            return false
        }

        override fun putIfGreater(key: Long, byteValue: Int): Boolean { // for 5 robots
            var key = key
            var nidx = key.toInt() and LOOKUP_MASK
            var nodeIndex = this.lookupArray[nidx]
            var nodeArray: IntArray
            key = key ushr LOOKUP_SHIFT
            var elementThis = (nidx ushr LOOKUP_SHIFT_2)
            var elementThisLookup = this.elementLookup[elementThis]
            //go through nodes (with compression because (key<<8)+value is inside "int" range now)
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                this.lookupArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key.toInt()) {
                    if (byteValue > prevVal) {  //putIfGreater
                        this.lookupArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                val nodeSize = this.nodeSizeLookup[elementThis]
                if (this.nextNode + nodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += nodeSize
                this.lookupArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                elementThis = key.toInt() and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray[nidx + this.elementLookup[prevKey and this.nodeMask]] =
                    ((prevKey ushr this.nodeShift).inv() shl 8) or prevVal
            } else {
                // -> node index is positive = go to next node
                elementThis = key.toInt() and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx += elementThisLookup
            //go through leaf node (with compression)
            nodeIndex = nodeArray[nidx]
            key = key ushr this.nodeShift
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key.toInt()) {
                    if (byteValue > prevVal) {  //putIfGreater
                        nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                if (this.nextNode + this.leafNodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += this.leafNodeSize
                nodeArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                nidx = (nodeIndex and NODE_ARRAY_MASK) + (prevKey and this.leafNodeMask)
                nodeArray[nidx] =
                    ((prevKey ushr this.leafNodeShift).inv() shl 8) or prevVal //negative
            } else {
                // -> node index is positive = go to next node
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx = (nodeIndex and NODE_ARRAY_MASK) + (key.toInt() and this.leafNodeMask)
            //get leaf (with compression)
            var leafIndex = nodeArray[nidx]
            key = key ushr this.leafNodeShift
            if (0 == leafIndex) {
                // -> leaf index is null = unused
                //write current value as a "compressed branch" (negative leaf index)
                //exit immediately because no leaf needs to be stored
                nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > leafIndex) {
                // -> leaf index is negative = used by a single "compressed branch"
                val prevKey = (leafIndex.inv()) shr 8
                val prevVal = 0xff and leafIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key.toInt()) {
                    if (byteValue > prevVal) {  //putIfGreater
                        nodeArray[nidx] = (leafIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new leaf
                if (this.nextLeaf >= this.nextLeafArray) {
                    if (this.leafArrays.size <= this.numLeafArrays) {
                        this.leafArrays =
                            this.leafArrays.copyOf<ByteArray>(this.leafArrays.size shl 1) as Array<ByteArray>
                    }
                    val newLeafArray = tryAllocateLeafArray()
                    if (newLeafArray == null) return false
                    this.leafArrays[this.numLeafArrays++] = newLeafArray
                    this.nextLeafArray += LEAF_ARRAY_SIZE
                }
                leafIndex = this.nextLeaf
                this.nextLeaf += this.leafSize
                nodeArray[nidx] = leafIndex
                //push the previous "compressed branch" further to the leaf
                val lidx = (leafIndex and LEAF_ARRAY_MASK) + (prevKey and this.leafMask)
                this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT][lidx] = prevVal.toByte()
            }
            val leafArray = this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT]
            val lidx = (leafIndex and LEAF_ARRAY_MASK) + (key.toInt() and this.leafMask)
            val prevVal = leafArray[lidx]
            if (byteValue > (0xff and prevVal.toInt())) {  //putIfGreater
                leafArray[lidx] = byteValue.toByte()
                return true
            }
            return false
        }

        override fun allocatedBytes(): Long {
            return super.allocatedBytes() + this.lookupArray.size * 4L
        }

        companion object {
            const val LOOKUP_SHIFT: Int = 3 * 8
            const val LOOKUP_SHIFT_2: Int = 2 * 8
            const val LOOKUP_MASK: Int = (1 shl LOOKUP_SHIFT) - 1
        }
    }


    /**
     * this class is used to find a larger number of distinct, equally good solutions,
     * especially those that share some robot positions and would normally be excluded
     * by the aggressive search tree pruning.
     * the methods "putIfGreater" are modified to behave like "putIfGreaterOrEqual".
     * (the code is copied from the super class, changed lines are marked with //putIfGreaterOrEqual)
     */
    private class KeyDepthMapTrieSpecial8BitEqual(board: Board) :
        KeyDepthMapTrieSpecial8Bit(board) {
        override fun putIfGreater(key: Int, byteValue: Int): Boolean { // for 4 robots
            var key = key
            var nidx = key and LOOKUP_MASK
            var nodeIndex = this.lookupArray[nidx]
            val nodeArray: IntArray
            key = key ushr LOOKUP_SHIFT
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                this.lookupArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key) {
                    if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                        this.lookupArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                if (this.nextNode + this.leafNodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += this.leafNodeSize
                this.lookupArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                nidx = (nodeIndex and NODE_ARRAY_MASK) + (prevKey and this.leafNodeMask)
                nodeArray[nidx] =
                    ((prevKey ushr this.leafNodeShift).inv() shl 8) or prevVal //negative
            } else {
                // -> node index is positive = go to next node
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx = (nodeIndex and NODE_ARRAY_MASK) + (key and this.leafNodeMask)
            //get leaf (with compression)
            var leafIndex = nodeArray[nidx]
            key = key ushr this.leafNodeShift
            if (0 == leafIndex) {
                // -> leaf index is null = unused
                //write current value as a "compressed branch" (negative leaf index)
                //exit immediately because no leaf needs to be stored
                nodeArray[nidx] = ((key.inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > leafIndex) {
                // -> leaf index is negative = used by a single "compressed branch"
                val prevKey = (leafIndex.inv()) shr 8
                val prevVal = 0xff and leafIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key) {
                    if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                        nodeArray[nidx] = (leafIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new leaf
                if (this.nextLeaf >= this.nextLeafArray) {
                    if (this.leafArrays.size <= this.numLeafArrays) {
                        this.leafArrays =
                            this.leafArrays.copyOf<ByteArray>(this.leafArrays.size shl 1) as Array<ByteArray>
                    }
                    val newLeafArray = tryAllocateLeafArray()
                    if (newLeafArray == null) return false
                    this.leafArrays[this.numLeafArrays++] = newLeafArray
                    this.nextLeafArray += LEAF_ARRAY_SIZE
                }
                leafIndex = this.nextLeaf
                this.nextLeaf += this.leafSize
                nodeArray[nidx] = leafIndex
                //push the previous "compressed branch" further to the leaf
                val lidx = (leafIndex and LEAF_ARRAY_MASK) + (prevKey and this.leafMask)
                this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT][lidx] = prevVal.toByte()
            }
            val leafArray = this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT]
            val lidx = (leafIndex and LEAF_ARRAY_MASK) + (key and this.leafMask)
            val prevVal = leafArray[lidx]
            if (byteValue >= (0xff and prevVal.toInt())) {  //putIfGreaterOrEqual
                leafArray[lidx] = byteValue.toByte()
                return true
            }
            return false
        }

        override fun putIfGreater(key: Long, byteValue: Int): Boolean { // for 5 robots
            var key = key
            var nidx = key.toInt() and LOOKUP_MASK
            var nodeIndex = this.lookupArray[nidx]
            var nodeArray: IntArray
            key = key ushr LOOKUP_SHIFT
            var elementThis = (nidx ushr LOOKUP_SHIFT_2)
            var elementThisLookup = this.elementLookup[elementThis]
            //go through nodes (with compression because (key<<8)+value is inside "int" range now)
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                this.lookupArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key.toInt()) {
                    if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                        this.lookupArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                val nodeSize = this.nodeSizeLookup[elementThis]
                if (this.nextNode + nodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += nodeSize
                this.lookupArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                elementThis = key.toInt() and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray[nidx + this.elementLookup[prevKey and this.nodeMask]] =
                    ((prevKey ushr this.nodeShift).inv() shl 8) or prevVal
            } else {
                // -> node index is positive = go to next node
                elementThis = key.toInt() and this.nodeMask
                nidx = (nodeIndex and NODE_ARRAY_MASK) - elementThisLookup - 1
                elementThisLookup = this.elementLookup[elementThis]
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx += elementThisLookup
            //go through leaf node (with compression)
            nodeIndex = nodeArray[nidx]
            key = key ushr this.nodeShift
            if (0 == nodeIndex) {
                // -> node index is null = unused
                //write current key+value as a "compressed branch" (negative node index)
                //exit immediately because no further nodes and no leaf need to be stored
                nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > nodeIndex) {
                // -> node index is negative = used by a single "compressed branch"
                val prevKey = (nodeIndex.inv()) shr 8
                val prevVal = 0xff and nodeIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key.toInt()) {
                    if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                        nodeArray[nidx] = (nodeIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new node
                if (this.nextNode + this.leafNodeSize > this.nextNodeArray) {
                    if (this.nodeArrays.size <= this.numNodeArrays) {
                        this.nodeArrays =
                            this.nodeArrays.copyOf<IntArray>(this.nodeArrays.size shl 1) as Array<IntArray>
                    }
                    val newNodeArray = tryAllocateNodeArray()
                    if (newNodeArray == null) return false
                    this.nodeArrays[this.numNodeArrays++] = newNodeArray
                    this.nextNode = this.nextNodeArray
                    this.nextNodeArray += NODE_ARRAY_SIZE
                }
                nodeIndex = this.nextNode
                this.nextNode += this.leafNodeSize
                nodeArray[nidx] = nodeIndex
                //push previous "compressed branch" one node further
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
                nidx = (nodeIndex and NODE_ARRAY_MASK) + (prevKey and this.leafNodeMask)
                nodeArray[nidx] =
                    ((prevKey ushr this.leafNodeShift).inv() shl 8) or prevVal //negative
            } else {
                // -> node index is positive = go to next node
                nodeArray = this.nodeArrays[nodeIndex ushr NODE_ARRAY_SHIFT]
            }
            nidx = (nodeIndex and NODE_ARRAY_MASK) + (key.toInt() and this.leafNodeMask)
            //get leaf (with compression)
            var leafIndex = nodeArray[nidx]
            key = key ushr this.leafNodeShift
            if (0 == leafIndex) {
                // -> leaf index is null = unused
                //write current value as a "compressed branch" (negative leaf index)
                //exit immediately because no leaf needs to be stored
                nodeArray[nidx] = ((key.toInt().inv()) shl 8) or byteValue //negative
                return true
            } else if (0 > leafIndex) {
                // -> leaf index is negative = used by a single "compressed branch"
                val prevKey = (leafIndex.inv()) shr 8
                val prevVal = 0xff and leafIndex
                //previous and current keys are equal (duplicate key)
                if (prevKey == key.toInt()) {
                    if (byteValue >= prevVal) {  //putIfGreaterOrEqual
                        nodeArray[nidx] = (leafIndex xor prevVal) or byteValue //negative
                        return true
                    }
                    return false
                }
                //previous and current keys are not equal
                //create a new leaf
                if (this.nextLeaf >= this.nextLeafArray) {
                    if (this.leafArrays.size <= this.numLeafArrays) {
                        this.leafArrays =
                            this.leafArrays.copyOf<ByteArray>(this.leafArrays.size shl 1) as Array<ByteArray>
                    }
                    val newLeafArray = tryAllocateLeafArray()
                    if (newLeafArray == null) return false
                    this.leafArrays[this.numLeafArrays++] = newLeafArray
                    this.nextLeafArray += LEAF_ARRAY_SIZE
                }
                leafIndex = this.nextLeaf
                this.nextLeaf += this.leafSize
                nodeArray[nidx] = leafIndex
                //push the previous "compressed branch" further to the leaf
                val lidx = (leafIndex and LEAF_ARRAY_MASK) + (prevKey and this.leafMask)
                this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT][lidx] = prevVal.toByte()
            }
            val leafArray = this.leafArrays[leafIndex ushr LEAF_ARRAY_SHIFT]
            val lidx = (leafIndex and LEAF_ARRAY_MASK) + (key.toInt() and this.leafMask)
            val prevVal = leafArray[lidx]
            if (byteValue >= (0xff and prevVal.toInt())) {  //putIfGreaterOrEqual
                leafArray[lidx] = byteValue.toByte()
                return true
            }
            return false
        }
    }

    companion object {
        protected const val NODE_ARRAY_SHIFT: Int =
            16 // 16 == 256KB (was 20==4MB; smaller arrays prevent OOM between memory checks)
        protected val NODE_ARRAY_SIZE: Int = 1 shl NODE_ARRAY_SHIFT
        protected val NODE_ARRAY_MASK: Int = NODE_ARRAY_SIZE - 1
        protected const val LEAF_ARRAY_SHIFT: Int =
            16 // 16 == 64KB (was 20==1MB; smaller arrays prevent OOM between memory checks)
        protected val LEAF_ARRAY_SIZE: Int = 1 shl LEAF_ARRAY_SHIFT
        protected val LEAF_ARRAY_MASK: Int = LEAF_ARRAY_SIZE - 1
        fun createInstance(board: Board, useMoreMemoryForSpeedup: Boolean): KeyDepthMapTrieSpecial {
            // The 8Bit variant allocates a 64MB lookup array - only use it if heap is large enough
            val maxHeapMB = Runtime.getRuntime().maxMemory() shr 20
            val heapLargeEnough = maxHeapMB > 768
            if (useMoreMemoryForSpeedup && heapLargeEnough && (8 == board.sizeNumBits) && ((4 == board.numRobots) || (5 == board.numRobots))) {
                if (Solver.USE_SLOW_SEARCH_MORE_SOLUTIONS) {
                    Logger.println("UseSlowSearchMoreSolutions")
                    return KeyDepthMapTrieSpecial8BitEqual(board)
                } else {
                    return KeyDepthMapTrieSpecial8Bit(board)
                }
            } else {
                if (Solver.USE_SLOW_SEARCH_MORE_SOLUTIONS) {
                    Logger.println("UseSlowSearchMoreSolutions")
                    return KeyDepthMapTrieSpecialEqual(board)
                } else {
                    return KeyDepthMapTrieSpecial(board)
                }
            }
        }
    }
}
